app/src/Entity/Room.php
<?php

namespace App\Entity;

use App\Repository\RoomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RoomRepository::class)]
class Room
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $capacityMaximum = null;

    #[ORM\OneToMany(mappedBy: 'room', targetEntity: Workshop::class)]
    private Collection $workshops;

    public function __construct()
    {
        $this->workshops = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCapacityMaximum(): ?int
    {
        return $this->capacityMaximum;
    }

    public function setCapacityMaximum(int $capacityMaximum): static
    {
        $this->capacityMaximum = $capacityMaximum;

        return $this;
    }

    /**
     * @return Collection<int, Workshop>
     */
    public function getJobs(): Collection
    {
        return $this->workshops;
    }

    public function addJob(Workshop $job): static
    {
        if (!$this->workshops->contains($job)) {
            $this->workshops->add($job);
            $job->setRoom($this);
        }

        return $this;
    }

    public function removeJob(Workshop $job): static
    {
        if ($this->workshops->removeElement($job)) {
            // set the owning side to null (unless already changed)
            if ($job->getRoom() === $this) {
                $job->setRoom(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name ?? '';
    }
}

app/src/Entity/Speaker.php
<?php

namespace App\Entity;

use App\Repository\SpeakerRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SpeakerRepository::class)]
class Speaker
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $socialEmail = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $resgistrationAt = null;

    #[ORM\ManyToMany(targetEntity: Workshop::class, mappedBy: 'speakers')]
    private Collection $workshops;

    #[ORM\ManyToOne(inversedBy: 'speakers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSocialEmail(): ?string
    {
        return $this->socialEmail;
    }

    public function setSocialEmail(string $socialEmail): static
    {
        $this->socialEmail = $socialEmail;

        return $this;
    }

    public function getResgistrationAt(): ?\DateTimeImmutable
    {
        return $this->resgistrationAt;
    }

    public function setResgistrationAt(?\DateTimeImmutable $resgistrationAt): static
    {
        $this->resgistrationAt = $resgistrationAt;

        return $this;
    }

    /**
     * @return Collection<int, Workshop>
     */
    public function getWorkshops(): Collection
    {
        return $this->workshops;
    }

    public function addWorkshop(Workshop $workshop): static
    {
        if (!$this->workshops->contains($workshop)) {
            $this->workshops->add($workshop);
            $workshop->addSpeaker($this);
        }

        return $this;
    }

    public function removeWorkshop(Workshop $workshop): static
    {
        if ($this->workshops->removeElement($workshop)) {
            $workshop->removeSpeaker($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }


    public function getUserId(): ?int
    {
        return $this->user->getId();
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
    public function __toString(): string
    {
        return $this->getUser()->getFirstName() . ' ' . $this->getUser()->getLastName();
    }
}

app/src/Entity/Workshop.php
<?php

namespace App\Entity;

use App\Repository\WorkshopRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: WorkshopRepository::class)]
class Workshop
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $startAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $endAt = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $description = null;

    #[ORM\OneToOne(inversedBy: 'workshop', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?Quiz $quiz = null;

    #[ORM\ManyToOne(inversedBy: 'workshops')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Room $room = null;
    
    #[ORM\ManyToOne(inversedBy: 'workshops')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Sector $sector = null;

    #[ORM\ManyToOne(inversedBy: 'workshops')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Edition $edition = null;
    
    #[ORM\OneToMany(mappedBy: 'workshop', targetEntity: Resource::class, orphanRemoval: true)]
    private Collection $resource;
    
    #[ORM\ManyToMany(targetEntity: Job::class, inversedBy: 'workshops')]
    private Collection $jobs;

    #[ORM\ManyToMany(targetEntity: Student::class, inversedBy: 'workshops')]
    private Collection $students;

    #[ORM\ManyToMany(targetEntity: Speaker::class, inversedBy: 'workshops')]
    private Collection $speakers;


    public function __construct()
    {
        $this->jobs = new ArrayCollection();
        $this->resource = new ArrayCollection();
        $this->students = new ArrayCollection();
        $this->speakers = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->name ?? '';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartAt(): ?\DateTimeImmutable
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTimeImmutable $startAt): static
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(\DateTimeImmutable $endAt): static
    {
        $this->endAt = $endAt;

        return $this;
    }

    /**
     * Retourne la durée de l'atelier au format HH:MM
     */
    public function getDuration(): ?string
    {
        if ($this->startAt && $this->endAt) {
            $interval = $this->startAt->diff($this->endAt);
            return $interval->format('%H:%I');
        }

        return null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }
    
    public function getQuiz(): ?Quiz
    {
        return $this->quiz;
    }

    public function setQuiz(Quiz $quiz): static
    {
        $this->quiz = $quiz;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): static
    {
        $this->room = $room;

        return $this;
    }

    public function getSector(): ?Sector
    {
        return $this->sector;
    }

    public function setSector(?Sector $sector): static
    {
        $this->sector = $sector;

        return $this;
    }

    public function getEdition(): ?Edition
    {
        return $this->edition;
    }

    public function setEdition(?Edition $edition): static
    {
        $this->edition = $edition;

        return $this;
    }

    /**
     * @return Collection<int, Ressource>
     */
    public function getResources(): Collection
    {
        return $this->resource;
    }

    public function addResource(Resource $resource): static
    {
        if (!$this->resource->contains($resource)) {
            $this->resource->add($resource);
            $resource->setWorkshop($this);
        }

        return $this;
    }

    public function removeResource(Resource $resource): static
    {
        if ($this->resource->removeElement($resource)) {
            // set the owning side to null (unless already changed)
            if ($resource->getWorkshop() === $this) {
                $resource->setWorkshop(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Job>
     */
    public function getJobs(): Collection
    {
        return $this->jobs;
    }

    public function addJob(Job $job): static
    {
        if (!$this->jobs->contains($job)) {
            $this->jobs->add($job);
        }

        return $this;
    }

    public function removeJob(Job $job): static
    {
        $this->jobs->removeElement($job);

        return $this;
    }

    /**
     * @return Collection<int, Student>
     */
    public function getStudents(): Collection
    {
        return $this->students;
    }

    public function addStudent(Student $student): static
    {
        if (!$this->students->contains($student)) {
            $this->students->add($student);
        }

        return $this;
    }

    public function removeStudent(Student $student): static
    {
        $this->students->removeElement($student);

        return $this;
    }

        /**
     * @return Collection<int, Speaker>
     */
    public function getSpeakers(): Collection
    {
        return $this->speakers;
    }

    public function addSpeaker(Speaker $speaker): static
    {
        if (!$this->speakers->contains($speaker)) {
            $this->speakers->add($speaker);
        }

        return $this;
    }

    public function removeSpeaker(Speaker $speaker): static
    {
        $this->speakers->removeElement($speaker);

        return $this;
    }

}

app/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class UserType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options): void
  {
    $builder
      ->add('firstName', TextType::class, [
        'label' => 'Prénom',
        'attr' => [
          'placeholder' => 'Prénom',
          'class' => 'form-control',
          'minlength' => 2,
          'maxlength' => 50
        ],
        'label_attr' => [
          'class' => 'form-label mt-4'
        ],
        'constraints' => [
          new Assert\NotBlank(),
          new Assert\Length(['min' => 2, 'max' => 50]),
        ],
      ])
      ->add('lastName', TextType::class, [
        'label' => 'Nom',
        'attr' => [
          'placeholder' => 'Nom complet',
          'class' => 'form-control',
          'minlength' => 2,
          'maxlength' => 50
        ],
        'label_attr' => [
          'class' => 'form-label mt-4'
        ],
        'constraints' => [
          new Assert\NotBlank(),
          new Assert\Length(['min' => 2, 'max' => 50]),
        ],
        'required' => false,
      ])
      ->add('email', EmailType::class, [
        'label' => 'Adresse email',
        'attr' => [
          'placeholder' => 'Adresse email',
          'class' => 'form-control',
          'minlength' => 4,
          'maxlength' => 180
        ],
        'label_attr' => [
          'class' => 'form-label mt-4'
        ],
        'constraints' => [
          new Assert\NotBlank(),
          new Assert\Length(['min' => 4, 'max' => 180]),
        ],
      ])
      ->add('plainPassword', PasswordType::class, [
        'label' => 'Mot de passe actuel',
        'attr' => [
          'placeholder' => 'Mot de passe actuel',
          'class' => 'form-control',
          'minlength' => 8,
          'maxlength' => 50
        ],
        'label_attr' => [
          'class' => 'form-label mt-4'
        ],
        'constraints' => [
          new Assert\NotBlank(),
          new Assert\Length(['min' => 8, 'max' => 50]),
        ],
      ])
      ->add('submit', SubmitType::class, [
        'label' => 'Enregistrer',
        'attr' => [
          'class' => 'btn btn-primary btn-block mt-4'
        ]
      ]);
  }

  public function configureOptions(OptionsResolver $resolver): void
  {
    $resolver->setDefaults([
      'data_class' => User::class,
    ]);
  }
}

app/templates/pages/user/speakers/workshop.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forum des métiers - Atelier
	{{ workshop.name }}
{% endblock %}

{% set remainingSeats = workshop.room.capacityMaximum - workshop.students|length %}

{% block body %}
	<div class="container">
		<div class="position-sticky top-0 bg-white z-1 py-4">
			<div class="row">
				<div class="col">
					<a href="{{ path('home.index') }}">Accueil</a>
					>
					<a href="{{ path('user.speakers.workspace', {'id': user.id}) }}">Liste des ateliers</a>
					>
					{{ workshop.name }}</div>
			</div>
			<div class="row justify-content-between align-items-center mt-4">
				<div class="col-auto">
					<h1>Atelier ”{{ workshop.name }}”</h1>
				</div>
				<div class="col-auto">
					{% if isOpened %}
						{% if remainingSeats <= 0 %}
							<a href="#" class="btn btn-danger btn-lg px-4 me-md-2 fw-bold">Complet 🥳</a>
						{% endif %}
					{% else %}
						<a href="#" class="btn btn-success btn-lg px-4 me-md-2 fw-bold">Terminé ✅</a>
					{% endif %}

				</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<h2>Informations</h2>
				<table class="table table-striped">
					<tbody>
						<tr>
							<th scope="row">Nom</th>
							<td class="col-10">{{ workshop.name }}</td>
						</tr>
						<tr>
							<th scope="row">Description</th>
							<td>{{ workshop.description }}</td>
						</tr>
						<tr>
							<th scope="row">Métiers</th>
							<td>
								<div class="d-flex flex-wrap">
									{% for job in workshop.jobs %}
										<div class="card border-success m-2" style="max-width: 20rem;">
											<div class="card-header">{{ job.name }}</div>
											<div class="card-body">
												<h4 class="card-title h5">Activités</h4>
												{% for activity in job.activities %}
													<span class="badge bg-info">{{ activity.name }}</span>
												{% endfor %}
												<h4 class="card-title h5">Compétences</h4>
												{% for skill in job.skills %}
													<span class="badge bg-success">{{ skill.name }}</span>
												{% endfor %}
											</div>
										</div>
									{% endfor %}
								</div>
							</td>
						</tr>
						<tr>
							<th scope="row">Secteur</th>
							<td>
								<div class="d-flex flex-wrap">
									<div class="card border-info m-2" style="max-width: 20rem;">
										<div class="card-header">{{ workshop.sector.name }}</div>
										<div class="card-body">
											<p class="card-text">{{ workshop.sector.description}}</p>
										</div>
									</div>
								</div>
							</td>
						</tr>
						<tr>
							<th scope="row">Nombre de places</th>
							<td>
								<span class="badge bg-primary rounded-pill">{{ workshop.room.capacityMaximum }}</span>
							</td>
						</tr>
						<tr>
							<th scope="row">Places restantes</th>
							<td>
								{% if isOpened %}
									{% if remainingSeats <= 0 %}
										<span class="badge bg-danger">Complet 😭</span>
									{% else %}
										<span class="badge bg-primary rounded-pill">{{ remainingSeats }}</span>
									{% endif %}
								{% else %}
									<span class="badge bg-success">Terminé ✅</span>
								{% endif %}

							</td>
						</tr>
						<tr>
							<th scope="row">Date</th>
							<td>{{ workshop.startAt|date('d/m/Y') }}</td>
						</tr>
						<tr>
							<th scope="row">Heure</th>
							<td>{{ workshop.startAt|date('H:i') }}</td>
						</tr>
						<tr>
							<th scope="row">Durée</th>
							<td>{{ workshop.duration }}</td>
						</tr>
						<tr>
							<th scope="row">Lieu</th>
							<td>{{ workshop.room.name }}</td>
						</tr>
						<tr>
							<th scope="row">Intervenant{{ (workshop.speakers|length > 1) ? 's' }}</th>
							<td>
								{% for speaker in workshop.speakers %}
									{{ speaker.user.firstname }}
									{{ speaker.user.lastname }}
									<br>
								{% else %}
									<span class="badge bg-warning">Pas encore d'intervenant de désigné</span>
								{% endfor %}
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>

		<div class="row mt-4">
			<div class="col">
				<div class="d-flex">
					<h2>Participants</h2>
					<p class="ms-2">
						<span class="badge bg-primary rounded-pill">{{ workshop.students|length }}
							/
							{{ workshop.room.capacityMaximum }}</span>
					</p>
				</div>
				<div class="table-responsive">
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col">Nom</th>
								<th scope="col">Prénom</th>
								<th scope="col">Ecole</th>
							</tr>
						</thead>
						<tbody>
							{% for student in workshop.students %}
								<tr>
									<td>{{ student.user.lastname }}</td>
									<td>{{ student.user.firstname }}</td>
									<td>{{ student.school.name }}</td>
								</tr>
							{% else %}
								<tr>
									<td class="table-warning" colspan="3">Personne n'est inscrit sur cet atelier</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="row mt-4">
			<div id="resources" class="d-flex justify-content-between align-bottom">
				<h2>Ressources</h2>
				<p class="mb-0 align-bottom">
					<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
						Ajouter
						<i class="fa-solid fa-file-import mx-2"></i>
					</a>
				</p>
				<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
					<div class="offcanvas-header">
						<h5 class="offcanvas-title" id="offcanvasExampleLabel">Ajouter une nouvelle ressource</h5>
						<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
					</div>
					<div class="offcanvas-body">
						<div>
							Indiquez ci-dessous un nom et une description pour la ressource que vous souhaitez ajouter à l'atelier.
						</div>
						<div class="dropdown mt-3">
							{{ form(form) }}
							</div>
						</div>
					</div>
				</div>
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col">Titre</th>
							<th scope="col">Description</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						{% for resource in workshop.resources %}
							<tr class="align-middle">
								<td>
									<div class="row">
										<div class="col-2"><img src="/img/pdf.png" alt="pdf file" width="20px"></div>
										<div class="col-10">{{ resource.name }}</div>
									</div>
								</td>
								<td>{{ resource.description }}</td>
								<td class="align-middle">
									<a class="btn btn-success" href="{{ resource.url }}" target="_blank">
										<i class="fa-solid fa-download"></i>
									</a>
									<a class="btn btn-danger" href="{{ path('user.speakers.workshop.resource.delete', {'user': user.id, 'workshop': workshop.id, 'resource': resource.id}) }}">
										<i class="fa-solid fa-trash"></i>
									</a>
								</td>
							</tr>
						{% else %}
							<tr>
								<td class="table-warning" colspan="3">Pas de resources fournies</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="row mt-4 mb-4">
				<div class="col">
					<a href="{{ path('user.speakers.workspace', {'id': user.id}) }}" class="btn btn-secondary">Retour aux ateliers</a>
				</div>
			</div>
		</div>
	{% endblock %}

app/templates/pages/user/speakers/workspace.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forum des métiers - Mes inscriptions aux ateliers
{% endblock %}

{% block body %}
	<div class="container mt-4">
		<h1>Liste des ateliers où vous intervenez</h1>
		<div class="count mt-4">
			Vous intervenez dans
			{{workshopsWithEnrollment|length}}
			{% if workshopsWithEnrollment|length > 1 %}
				ateliers.
			{% else %}
				atelier.
			{% endif %}
		</div>
		<table class="table table-hover table-striped mt-4">
			<thead class="position-sticky top-0">
				<tr class="table-dark">
					<th scope="col" class="col-3">Atelier</th>
					<th scope="col" class="col-auto">Description</th>
					<th scope="col" class="col-2">Date & durée</th>
					<th scope="col" class="col-1">Consulter</th>
				</tr>
			</thead>
			<tbody>
				{% for workshopData in workshopsWithEnrollment %}
					{% set workshop = workshopData.workshop %}
					{% set isFinished = workshopData.isFinished %}
					{% set studentCount = workshopData.studentCount %}
					{% set roomCapacity = workshopData.roomCapacity %}
					{% set isFull = workshopData.isFull %}

					<tr class="{{ (isFinished) ? 'table-dark' : '' }}">
						<td class="align-top">
							<a style="color:black;text-decoration:none" href="{{ path('workshop-registration.show', {'id': workshop.id}) }}">
								<h2 class="h5">{{ workshop.name }}</h2>
							</a>
							{% if isFinished %}
								<br><span class="badge bg-danger">Terminé</span>
							{% endif %}
							{% if isFull %}
								<br><span class="badge bg-warning">Complet</span>
							{% else %}
								<br>Places :
								{{ studentCount }}
								/
								{{ roomCapacity }}
							{% endif %}
						</td>
						<td>{{ workshop.description}}<br>
							<strong>Intervenants :</strong>
							{% for speaker in workshop.speakers %}
								{% if user == speaker.user %}
									<span class="badge bg-info">Vous</span>
								{% else %}
									<span class="badge bg-success">{{ speaker.user.firstName }}
										{{ speaker.user.lastName }}</span>
								{% endif %}
							{% endfor %}
							<br>
						</td>
						<td class="align-middle">{{ workshop.startAt | format_datetime(locale='fr') }}<br>
							{{ workshop.duration }}
							heures
						</td>
						<td class="align-middle text-center">
							<a class="btn btn-success" href="{{ path('user.speakers.workshop', {'user': user.id, 'workshop': workshop.id}) }}">
								<i class="fa-solid fa-eye"></i>
							</a>
						</td>
					</tr>
				{% else %}
					<tr>
						<td class="table-secondary" colspan="4">Pas d'inscriptions trouvées</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

	</div>
{% endblock %}